---
title: "CodeBook"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Introduction
This codebook describes  all variables along with units and an explaination of what the variables are. This data set was generated from data availible at <http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones>. 

## Description of Source Data
The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

Check the README.txt file for further details about this dataset.

A video of the experiment including an example of the 6 recorded activities with one of the participants can be seen in the following link: [Web Link]

An updated version of this dataset can be found at [Web Link]. It includes labels of postural transitions between activities and also the full raw inertial signals instead of the ones pre-processed into windows.

Attribute Information:

For each record in the dataset it is provided:

* Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
* Triaxial Angular velocity from the gyroscope.
* A 561-feature vector with time and frequency domain variables.
* Its activity label.
* An identifier of the subject who carried out the experiment.

## Processing of Source Data
The scritp run_analysis.R does the following

1. Merges the training and the test sets to create one data set.
2, Extracts only the measurements on the mean and standard deviation for each measurement.
3, Uses descriptive activity names to name the activities in the data set
4, Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
    
## Naming Adjustments
Substitutions were done on the source variable names to make them descriptive. I used camel-case names to make them easily readable These substitutions are:

1. Change "t" to time at the begining of the column name
1. CHange "Freq" to "Frequency" 
1. Change "Acc" to the more descriptive "Acceleration"
1. Change "Gyro" to "Gyroscope" in case anyone confused it with a greek sandwich
5. Change "Mag" to "Magnitude"
6. Spelled out "std" to "StandardDevation" even though it is quite long
7. Changed "mean" to "Mean" to keep with my choice of camel-case names
8. Removed special characters "()" and "-"

## Output Dataset
The output data set has been grouped by the ActivityDSC and the SubjectID. ActivityDSC comes from the activity_labes file in the source data set. SubjectID is from the subject_test and subject_trial files.  It a number used to identify the subjects of the experiment.  The output data only has the mean of each variable from the source data set. The source data set had means and standard deviations in it.  THe output is mean of these means and standard deviations.  This provides a summary of these values that has 180 observations in it instead of the full >10000 observations in the source dataset.

